#!/bin/bash

set -euxo pipefail

# push latest arm32v7 image
docker push "sebastianalbers/spotify-ripper:latest-arm32v7"

# read version from Docker container
version=$(./read-version.sh amd64)

# push multi-arch image
./push-multi-arch-image.sh "${version}"
